export const LOADING_OPEN='LOADING_OPEN';
export const LOADING_CLOSED='LOADING_CLOSED';
export const ALERT_INIT='ALERT_INIT';
export const ALERT_CANCEL='ALERT_CANCEL';
export const SEARCH_HISTORY_INIT='SEARCH_HISTORY_INIT';
export const SEARCH_HISTORY_UPDATE='SEARCH_HISTORY_UPDATE';
export const SEARCH_EVENT='SEARCH_EVENT';