export const LOADING_OPEN='LOADING_OPEN';
export const LOADING_CLOSED='LOADING_CLOSED';
export const ALERT_INIT='ALERT_INIT';
export const ALERT_CANCEL='ALERT_CANCEL';
export const SEARCH_HISTORY_INIT='SEARCH_HISTORY_INIT';
export const SEARCH_HISTORY_UPDATE='SEARCH_HISTORY_UPDATE';
export const SEARCH_EVENT='SEARCH_EVENT';
export const PLAYER_EVENT_INIT='PLAYER_EVENT_INIT';
export const PLAYER_EVENT_PLAY='PLAYER_EVENT_PLAY';
export const PLAYER_EVENT_PROCESS='PLAYER_EVENT_PROCESS';
export const PLAYER_EVENT_PAUSE='PLAYER_EVENT_PAUSE';
export const PLAYER_EVENT_NEXT='PLAYER_EVENT_NEXT';
export const PLAYER_EVENT_PREVIOUS='PLAYER_EVENT_PREVIOUS';
export const PLAYER_EVENT_TOGGLE='PLAYER_EVENT_TOGGLE';
export const PLAYER_EVENT_TOGGLE_PLAY_TYPE='PLAYER_EVENT_TOGGLE_PLAY_TYPE';
export const PLAYER_EVENT_BUFFERED='PLAYER_EVENT_BUFFERED';
export const PLAYER_EVENT_PLAY_ORDER='PLAYER_EVENT_PLAY_ORDER';
export const PLAYER_EVENT_SET_CURRENT='PLAYER_EVENT_SET_CURRENT';
export const PLAYER_EVENT_UPDATE_PLAYLIST='PLAYER_EVENT_UPDATE_PLAYLIST';
export const PLAYER_EVENT_UPDATE_lIST='PLAYER_EVENT_UPDATE_lIST';
export const PLAYER_EVENT_UPDATE_PLAY_ORDER_INDEX='PLAYER_EVENT_UPDATE_PLAY_ORDER_INDEX';


export const USER_EVENT_UPDATE_PLAYER='USER_EVENT_UPDATE_PLAYER';
